# Generated by Django 5.2.6 on 2025-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of this product or feature"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this product is currently active"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owner_team",
            field=models.CharField(
                blank=True,
                help_text="Team responsible for this product",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default="medium",
                help_text="Business priority of this product",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
