# Generated by Django 5.2.6 on 2025-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="azureresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("webapp", "Web App"),
                    ("function", "Function App"),
                    ("app_service_plan", "App Service Plan"),
                    ("sql_db", "SQL Database"),
                    ("sql_server", "SQL Server"),
                    ("cosmos_db", "Cosmos DB"),
                    ("storage", "Storage Account"),
                    ("keyvault", "Key Vault"),
                    ("managed_identity", "Managed Identity"),
                    ("vnet", "Virtual Network"),
                    ("app_gateway", "Application Gateway"),
                    ("load_balancer", "Load Balancer"),
                    ("public_ip", "Public IP Address"),
                    ("nsg", "Network Security Group"),
                    ("vm", "Virtual Machine"),
                    ("container", "Container Instance"),
                    ("container_registry", "Container Registry"),
                    ("app_insights", "Application Insights"),
                    ("autoscale", "Autoscale Setting"),
                    ("alert_rule", "Alert Rule"),
                    ("portal_dashboard", "Portal Dashboard"),
                    ("ssl_cert", "SSL Certificate"),
                    ("webhook", "Webhook"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
