# Generated by Django 5.2.6 on 2025-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure", "0002_alter_azureresource_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="azureresource",
            name="custom_metrics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom metrics to collect",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="azureresource",
            name="tags",
            field=models.JSONField(
                blank=True, default=dict, help_text="Resource tags", null=True
            ),
        ),
    ]
