# Generated by Django 5.2.6 on 2025-09-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0001_initial"),
        ("sentry", "0004_sentryissue_environment_sentryissue_logger_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentryjiralink",
            name="sentry_issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_link",
                to="sentry.sentryissue",
            ),
        ),
    ]
