# Generated by Django 5.2.6 on 2025-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardRefreshLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled Refresh"),
                            ("on_demand", "On-Demand Refresh"),
                            ("expired_only", "Expired Only Refresh"),
                            ("force_all", "Force Refresh All"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dashboard_types",
                    models.JSONField(
                        default=list, help_text="List of dashboard types refreshed"
                    ),
                ),
                ("snapshots_refreshed", models.PositiveIntegerField(default=0)),
                ("snapshots_failed", models.PositiveIntegerField(default=0)),
                ("total_generation_time", models.FloatField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Dashboard Refresh Log",
                "verbose_name_plural": "Dashboard Refresh Logs",
                "db_table": "dashboard_refresh_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Overview"),
                            ("product", "Product Health"),
                            ("environment", "Environment Status"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "filter_key",
                    models.CharField(
                        help_text="Unique key for filter combination (e.g., 'product_5_env_production')",
                        max_length=200,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Complete dashboard data ready for display"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this snapshot should be refreshed"
                    ),
                ),
                (
                    "generation_time",
                    models.FloatField(
                        help_text="Time taken to generate this snapshot (seconds)"
                    ),
                ),
                (
                    "data_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Size of JSON data in bytes"
                    ),
                ),
                (
                    "source_record_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of source records processed"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="Whether this snapshot is still valid"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Snapshot",
                "verbose_name_plural": "Dashboard Snapshots",
                "db_table": "dashboard_snapshots",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["dashboard_type", "filter_key"],
                        name="dashboard_s_dashboa_e5e6fb_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="dashboard_s_expires_154cc0_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="dashboard_s_generat_3211c7_idx"
                    ),
                ],
                "unique_together": {("dashboard_type", "filter_key")},
            },
        ),
    ]
