# Generated by Django 5.2.6 on 2025-09-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentryorganization",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
