# Generated by Django 5.2.6 on 2025-09-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("sentry", "0002_alter_sentryorganization_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentryproject",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.product",
            ),
        ),
    ]
