# Generated by Django 5.2.6 on 2025-09-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0003_sentryproject_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentryissue",
            name="environment",
            field=models.CharField(
                blank=True,
                help_text="Environment where this issue occurs (prod, staging, dev, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sentryissue",
            name="logger",
            field=models.CharField(
                blank=True,
                help_text="Logger name that generated this issue",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sentryissue",
            name="platform",
            field=models.CharField(
                blank=True,
                help_text="Platform/technology (javascript, python, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sentryissue",
            name="release",
            field=models.CharField(
                blank=True,
                help_text="Release version when this issue occurred",
                max_length=200,
                null=True,
            ),
        ),
    ]
